WeBudget/Models/Rashod.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WeBudget.Models
{
    public class Rashod
    {
        public int Id { get; set; }

        public int Day { get; set; }

        public int Month { get; set; }

        public double Sum { get; set; }

        public string Comment { get; set; }

        public  User User { get; set; }


    }
}

WeBudget/Controllers/RashodController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeBudget.Models;
using WeBudget.Service;

namespace WeBudget.Controllers
{
    public class RashodController : Controller
    {
        RashodService rashodservice = new RashodService();

        [HttpGet]
        public ActionResult EditRashod(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            
            if (rashodservice.findRashodById(id) != null)
            {
                return View(rashodservice.findRashodById(id));
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult EditRashod(Rashod rashod)

        {
            rashodservice.Edit(rashod);
            return RedirectToAction("Rashods");
        }

        [HttpGet]
        public ActionResult CreateRashod()

        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateRashod(Rashod rashod)
        {
            rashodservice.Create(rashod);
            return RedirectToAction("Rashods");
        }


        public ActionResult DeleteRashod(int id)
        {
            rashodservice.Delete(id);
            return RedirectToAction("Rashods");
        }


        public ActionResult Rashods()
        {
            BudgetContext db = new BudgetContext();
            // return View(rashodservice.getList());
            return View(db.Rashods);
        }
        protected override void Dispose(bool disposing)
        {
            rashodservice.Dispose();
            base.Dispose(disposing);
        }
    }
}

WeBudget/Views/Rashod/CreateRashod.cshtml
@{
    ViewBag.Title = "CreateRashod";
}


@model WeBudget.Models.Rashod

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавить расход</h2>

@using (Html.BeginForm())
{

    @Html.LabelFor(model => model.Day, "День")
    <br />
    @Html.EditorFor(model => model.Day)
    <br /><br />
    @Html.LabelFor(model => model.Month, "Месяц")
    <br />
    @Html.EditorFor(model => model.Month)
    <br /><br />
    @Html.LabelFor(model => model.Sum, "Сумма")
    <br />
    @Html.EditorFor(model => model.Sum)
    <br /><br />
    @Html.LabelFor(model => model.Comment, "Комментарий")
    <br />
    @Html.EditorFor(model => model.Comment)
    <br /><br />
    <input type="submit" value="Добавить" />
}

WeBudget/Views/Rashod/EditRashod.cshtml
@{
    ViewBag.Title = "EditRashod";
}

<h2>EditRashod</h2>

@{
    ViewBag.Title = "Редактировать расход";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model WeBudget.Models.Rashod
<h2>Расход № @Model.Id</h2>
@using (Html.BeginForm("EditRashod", "Rashod", FormMethod.Post))
{
    <fieldset>
        @Html.HiddenFor(m => m.Id)
        <p>
            @Html.LabelFor(m => m.Day, "День")
            <br />
            @Html.EditorFor(m => m.Day)
        </p>
        <p>
            @Html.LabelFor(m => m.Month, "Месяц")
            <br />
            @Html.EditorFor(m => m.Month)

        </p>
        <p>
            @Html.LabelFor(m => m.Sum, "Сумма")
            <br />
            @Html.EditorFor(m => m.Sum)
        </p>

        <p>
            @Html.LabelFor(m => m.Comment, "Комментарий")
            <br />
            @Html.EditorFor(m => m.Comment)
        </p>
        @Html.HiddenFor(m => m.UserId)
        <p><input type="submit" value="Отправить" /></p>
    </fieldset>
}

WeBudget/Views/Rashod/Rashods.cshtml
@{
    ViewBag.Title = "Rashods";
}


@model IEnumerable<WeBudget.Models.Rashod>
@{
    Layout = null;
}


<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <title>MуBudget</title>
    <link rel="stylesheet" href="~/Content/styles.css" type="text/css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300" type="text/css" />

    <title>Выравнивание фотографии по центру</title>
</head>




<style>
    .fig {
        text-align: center; /* Выравнивание по центру */
    }


    .center {
        width: 700px; /* Ширина элемента в пикселах */
        padding: 10px; /* Поля вокруг текста */
        margin: auto; /* Выравниваем по центру */
    }
</style>


<p class="fig">
    <img src="~/img/CY2NYGSvMto.jpg"
         width="1263" height="320" alt="Фотография">
</p>

<div class="center">
    <nav>
        <ul class="top-menu">
            <li><a href="index">ГЛАВНАЯ</a></li>
            <li class="About">О САЙТЕ</li>
            <li><a href="Contact">ОБРАТНАЯ СВЯЗЬ</a></li>
        </ul>
    </nav>
</div>
    <aside>
        <nav>
            <ul class="aside-menu">
                <li><a href="Table">ТАБЛИЦА РАСХОДОВ</a></li>
                <li><a href="Dohodi">ДОХОДЫ И РАСХОДЫ</a></li>
                <li><a href="Kakebo">KAKEBO</a></li>

            </ul>
        </nav>
    </aside>



    <div class="center">
        <h2>Расходы</h2>


        @{ var grid = new WebGrid(Model); }
        <div>
            @grid.GetHtml(columns: grid.Columns(
                                               grid.Column("Id", "№"),
                                               grid.Column("Day", "День"),
                                               grid.Column("Month", "Месяц"),
                                               grid.Column("Sum", "Сумма"),
                                               grid.Column("Comment", "Комментарий"),
                                               grid.Column("Редактировать", format: @<a href="~/Rashod/EditRashod/@item.Id"> Редактировать</a>),
                                                  grid.Column("Удалить", format: @<a href="~/Rashod/DeleteRashod/@item.Id"> Удалить</a>)
                                                     ), tableStyle: "table-bordered")
        </div>
        <input type="button" value="Добавить" onClick='location.href="CreateRashod"'>

    </div>

    <footer>
        <div id="footer">
            <div id="tw">
                <h3>16-09-2018</h3>
                <p>
                    Хорошо составленный годовой бюджет позволяет жить, не залезая в долги, значительную часть года.
                </p>
            </div>
            <div id="sitemap">
                <h3>О САЙТЕ</h3>
                <div>
                    <a href="Contact">Обратная связь</a>
                    <a href="About">О проекте</a>
                </div>
            </div>
        </div>
    </footer>