WeBudget/Models/ZdanieForArenda.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WeBudget.Models
{
    public class ZdanieForArenda
    {
        
        public int Id { get; set; }

        public string Date { get; set; }

        public double Sum { get; set; }

        public string Comment { get; set; }

        public int User { get; set; }
    }
}

WeBudget/Controllers/ZdanieForArendaController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WeBudget.Models;
using WeBudget.Service;

namespace WeBudget.Controllers
{
    public class ZdanieForArendaController : Controller
    {
        CRUDManagerForArenda zdanieForArendaService;
         
        public ZdanieForArendaController()
        {
            string dataStore = ConfigurationManager.AppSettings["DataStore"].ToString();
            switch (dataStore)
            {
                case "DB":
                    zdanieForArendaService = new ZdanieForArendaService();
                    break;
                case "File":
                    zdanieForArendaService = new ZdanieForArendaFileService();
                    break;
            }
        }

        [HttpGet]
        public ActionResult EditZdanieForArenda(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            
            if (zdanieForArendaService.findZdanieForArendaById(id) != null)
            {
                return View(zdanieForArendaService.findZdanieForArendaById(id));
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult UpdateZdanieForArenda(ZdanieForArenda zdanieForArenda)

        {
            zdanieForArendaService.Edit(zdanieForArenda);
            return RedirectToAction("ZdanieForArendas");
        }

        [HttpGet]
        public ActionResult CreateZdanieForArenda()

        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateZdanieForArenda(ZdanieForArenda zdanieForArenda)
        {
            zdanieForArendaService.Create(zdanieForArenda);
            return RedirectToAction("ZdanieForArendas");
        }


        public ActionResult DeleteZdanieForArenda(int id)
        {
            zdanieForArendaService.Delete(id);
            return RedirectToAction("ZdanieForArendas");
        }


        public ActionResult ZdanieForArendas()
        {
            JavaScriptSerializer js = new JavaScriptSerializer();
            ConstructionCompanyContext db = new ConstructionCompanyContext();
            string json = js.Serialize(db.ZdanieForArendas);
            return Content(json, "application/json");
        }
    }
}

WeBudget/Views/ZdanieForArenda/CreateZdanieForArenda.cshtml
@Scripts.Render("~/scripts/jquery.validate.min.js")
@Scripts.Render("~/scripts/jquery-1.10.2.js")
@Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")

@{
    ViewBag.Title = "Создать здание для аренды";
}

<!--секция скриптов-->
@section Scripts {
    @Scripts.Render("~/scripts/validate.min.js")
}

<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <title>О Компании</title>
    <link rel="stylesheet" href="~/Content/styles.css" type="text/css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300" type="text/css" />
    <title>Выравнивание фотографии по центру</title>
</head>

<p class="fig">
    <img src="~/img/home.jpg"
         width="1263" height="320" alt="Фотография">
</p>

<style>
    .fig {
        text-align: center; /* Выравнивание по центру */
    }


    .center {
        width: 700px; /* Ширина элемента в пикселах */
        padding: 10px; /* Поля вокруг текста */
        margin: auto; /* Выравниваем по центру */
    }
</style>


<div id="wrapper" ">

    <nav>

        <ul class="top-menu">
            <li>@Html.ActionLink("Главная", "Home", "Home")</li>
            <li>@Html.ActionLink("О компании", "About", "Home")</li>
            <li>@Html.ActionLink("Клиентам", "Customers", "Home")</li>
            <li>@Html.ActionLink("Проекты", "Project", "Home")</li>
            <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
        </ul>

    </nav>



    @model WeBudget.Models.ZdanieForArenda

    @{
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h2>Добавить здание для аренды</h2>

    <script type="text/javascript">
        function checkForm() {

            var comment = document.getElementById('Comment').value;

            if (comment < 30) {
                alert("введите комментрарий более 30 символов");
                return false;
            }
            else {
                return true;
            }
        }




    </script>



    @{Html.EnableClientValidation();}
    @{Html.EnableUnobtrusiveJavaScript();}
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)


        @Html.LabelFor(model => model.Date, "Дата постройки")
        <br />
        @Html.EditorFor(model => model.Date)
        <br /><br />
        @Html.LabelFor(model => model.Sum, "Стоимость здания")
        <br />
        @Html.EditorFor(model => model.Sum)
        <br /><br />
        @Html.LabelFor(model => model.Comment, "Дополнительная информация")
        <br />
        @Html.EditorFor(model => model.Comment)
        @Html.ValidationMessageFor(model => model.Comment)
        <br /><br />
        <input type="submit" value="Добавить" />
    }



</div>



<footer>
    <div id="footer">
        <div id="twitter">
            <h3>Связаться с нами</h3>
            <time datetime="2012-10-23"><a href="#">25.09</a></time>
            <p>
                Наши контакты:
                Телефон +7 000 000 00 00
            </p>
            <p>
                e-mail: samistroim@gmail.com
            </p>
        </div>
        <div id="sitemap">
            <h3>Карта сайта</h3>
            <div>
                <a href="C:\Users\User\Desktop\www.construction/home.html">Главная</a>
                <a href="C:\Users\User\Desktop\www.construction/abaut.html">О нас</a>
            </div>
            <div>
                <a href="C:\Users\User\Desktop\www.construction/customers.html">Клиентам</a>
                <a href="C:\Users\User\Desktop\www.construction/contact.html">Контакты</a>
            </div>
        </div>
        <div id="social">
            <h3>Социальные сети:</h3>
            <a href="http://plus.google.com/" class="social-icon google-plus"></a>
            <a href="http://instagram.com/" class="social-icon-small instagram"></a>
            <a href="https://vk.com/" class="social-icon-small vk"></a>
        </div>
        <div id="footer-logo">
            <a href="/"><img src="images/footer-logo.png" alt="Whitesquare logo"></a>

        </div>
    </div>
</footer>

WeBudget/Views/ZdanieForArenda/EditZdanieForArenda.cshtml
@{
    ViewBag.Title = "EditZdanieForArenda";
}

<h2>EditZdanieForArenda</h2>

@{
    ViewBag.Title = "Редактировать здание для аренды";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model WeBudget.Models.ZdanieForArenda
<h2>Здание для аренды № @Model.Id</h2>
@using (Html.BeginForm("UpdateZdanieForArenda", "ZdanieForArenda", FormMethod.Post))
{
    <fieldset>
        @Html.HiddenFor(m => m.Id)
        <p>
            @Html.LabelFor(m => m.Date, "Дата постройки")
            <br />
            @Html.EditorFor(m => m.Date)
        </p>
        <p>
            @Html.LabelFor(m => m.Sum, "Стоимость постройки")
            <br />
            @Html.EditorFor(m => m.Sum)
        </p>

        <p>
            @Html.LabelFor(m => m.Comment, "Дополнительная информация")
            <br />
            @Html.EditorFor(m => m.Comment)
        </p>
        @Html.HiddenFor(m => m.User)
        <p><input type="submit" value="Отправить" /></p>
    </fieldset>
}

WeBudget/Views/ZdanieForArenda/ZdanieForArendas.cshtml
@{
    ViewBag.Title = "ZdanieForArendas";
}


@model IEnumerable<WeBudget.Models.ZdanieForArenda>
@{
    Layout = null;
}


<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <title>Строительная компания</title>
    <link rel="stylesheet" href="~/Content/styles.css" type="text/css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300" type="text/css" />

    <title>Выравнивание фотографии по центру</title>
</head>




<style>
    .fig {
        text-align: center; /* Выравнивание по центру */
    }


    .center {
        width: 700px; /* Ширина элемента в пикселах */
        padding: 10px; /* Поля вокруг текста */
        margin: auto; /* Выравниваем по центру */
    }
</style>


<p class="fig">
    <img src="~/img/home.jpg"
         width="1263" height="320" alt="Фотография">
</p>

<div class="center">
    <nav>
        <ul class="top-menu">
            <li><a href="index">ГЛАВНАЯ</a></li>
            <li class="About">О САЙТЕ</li>
            <li><a href="Contact">ОБРАТНАЯ СВЯЗЬ</a></li>
        </ul>
    </nav>
</div>
    <aside>
        <nav>
            <ul class="aside-menu">
                <li><a href="Table">ссылка1</a></li>
                <li><a href="Dohodi">ссылка2</a></li>
                <li><a href="Kakebo">ссылка3</a></li>

            </ul>
        </nav>
    </aside>



    <div class="center">
        <h2>Здания для аренды</h2>


        @{ var grid = new WebGrid(Model); }
        <div>
            @grid.GetHtml(columns: grid.Columns(
                                                     grid.Column("Id", "№"),
                                                     grid.Column("Date", "Дата постройки"),
                                                     grid.Column("Sum", "Стоимость здания"),
                                                     grid.Column("Comment", "Дополнительная информация"),
                                                     grid.Column("Редактировать", format: @<a href="~/ZdanieForArenda/EditZdanieForArenda/@item.Id"> Редактировать</a>),
                                                     grid.Column("Удалить", format: @<a href="~/ZdanieForArenda/DeleteZdanieForArenda/@item.Id"> Удалить</a>)
                                                             ), tableStyle: "table-bordered")
        </div>
        <input type="button" value="Добавить" onClick='location.href="CreateZdanieForArenda"'>

    </div>

    