WeBudget/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WeBudget.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Home()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Customers()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Project()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
    }
}

WeBudget/Controllers/ZdanieForPokupkaController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeBudget.Models;
using WeBudget.Service;

namespace WeBudget.Controllers
{
    public class ZdanieForPokupkaController : Controller
    {
        CRUDManagerForPokupka zdanieForPokupkaService;

        public ZdanieForPokupkaController()
        {
            string dataStore = ConfigurationManager.AppSettings["DataStore"].ToString();
            switch (dataStore)
            {
                case "DB":
                    zdanieForPokupkaService = new ZdanieForPokupkaService();
                    break;
                case "File":
                    zdanieForPokupkaService = new ZdanieForPokupkaFileService();
                    break;
            }
        }

        [HttpGet]
        public ActionResult EditZdanieForPokupka(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
           
            if (zdanieForPokupkaService.findZdanieForPokupkaById(id) != null)
            {
                return View(zdanieForPokupkaService.findZdanieForPokupkaById(id));
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult UpdateZdanieForPokupka(ZdanieForPokupka zdanieForPokupka)
        {
            zdanieForPokupkaService.Edit(zdanieForPokupka);
            return RedirectToAction("ZdanieForPokupkas");
        }
   
        [HttpGet]
        public ActionResult CreateZdanieForPokupka()

        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateZdanieForPokupka(ZdanieForPokupka zdanieForPokupka)
        {
            zdanieForPokupkaService.Create(zdanieForPokupka);
            return RedirectToAction("ZdanieForPokupkas");
        }

        public ActionResult DeleteZdanieForPokupka(int id)
        {
            zdanieForPokupkaService.Delete(id);
            return RedirectToAction("ZdanieForPokupkas");
        }

        public ActionResult ZdanieForPokupkas()
        {
            return View(zdanieForPokupkaService.getList());
        }

        protected override void Dispose(bool disposing)
        {
            zdanieForPokupkaService.Dispose();
            base.Dispose(disposing);
        }
    }
}

WeBudget/Views/Home/About.cshtml
@{
    ViewBag.Title = "О компании";
}

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <title>О Компании</title>
    <link rel="stylesheet" href="~/Content/styles.css" type="text/css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300" type="text/css" />
    <title>Выравнивание фотографии по центру</title>

    <meta content="width=device-width, initial-scale=1, maximum-scale=0.8" name="viewport" />
</head>

<div class="card mb-3">
    <img class="card-img-top" src="~/img/home.jpg" alt="Card image cap">
</div>

<style>
    .fig {
        text-align: center; /* Выравнивание по центру */
    }


    .center {
        width: 700px; /* Ширина элемента в пикселах */
        padding: 10px; /* Поля вокруг текста */
        margin: auto; /* Выравниваем по центру */
    }
</style>


<body>
    <div id="wrapper">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Меню</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                       <a class="nav-item nav-link">
                            @Html.ActionLink("Главная", "Home", "Home")
                        </a>
                        <a class="nav-item nav-link">
                            @Html.ActionLink("О компании", "About", "Home")
                        </a>
                        <a class="nav-item nav-link">
                            @Html.ActionLink("Клиентам", "Customers", "Home")
                        </a>
                        <a class="nav-item nav-link">
                            @Html.ActionLink("Проекты", "ZdanieForPokupkas", "ZdanieForPokupka")
                        </a>
                        <a class="nav-item nav-link">
                            @Html.ActionLink("Контакты", "Contact", "Home")
                        </a>
                </div>
            </div>
        </nav>


        <div id="heading"></div>

        <p>
            Иванов Иван Иванович, директор и единственный работник Строительной компании "Что нам стоит"
        </p>
        <p>Иванов Иван Иванович почетный строитель Зеленогорзка. Под его руководством еще ничего не построили, но и не сломали</p>
        <p>Верьте</p>



    </div>
</body>

    <footer>
        <div class="card mb-3">
            <img class="card-img-top" src="~/img/footer.jpg" alt="Card image cap">
            <div class="card-body text-info">
                <h5 class="card-title">Связаться с нами</h5>
                <p class="card-body text-info">
                    Наши контакты:
                    Телефон +7 000 000 00 00    e-mail: samistroim@gmail.com
                </p>
            </div>
        </div>
    </footer>

<head/>

WeBudget/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Контакты";
}

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <title>Контакты</title>
    <link rel="stylesheet" href="~/Content/styles.css" type="text/css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300" type="text/css" />
    <title>Выравнивание фотографии по центру</title>
</head>

<div class="card mb-3">
    <img class="card-img-top" src="~/img/home.jpg" alt="Card image cap">
</div>

<style>
    .fig {
        text-align: center; /* Выравнивание по центру */
    }
    .center {
        width: 700px; /* Ширина элемента в пикселах */
        padding: 10px; /* Поля вокруг текста */
        margin: auto; /* Выравниваем по центру */
    }
</style>

<body>
    <div id="wrapper">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Меню</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link">
                        @Html.ActionLink("Главная", "Home", "Home")
                    </a>
                    <a class="nav-item nav-link">
                        @Html.ActionLink("О компании", "About", "Home")
                    </a>
                    <a class="nav-item nav-link">
                        @Html.ActionLink("Клиентам", "Customers", "Home")
                    </a>
                    <a class="nav-item nav-link">
                        @Html.ActionLink("Проекты", "ZdanieForPokupkas", "ZdanieForPokupka")
                    </a>
                    <a class="nav-item nav-link">
                        @Html.ActionLink("Контакты", "Contact", "Home")
                    </a>
                </div>
            </div>
        </nav>

        <blockquote>
            <p>
                Адресс компании:

            </p>
            <p>
                г. Ростов-на-Дону, пл. Толстого, д. 1/2

            </p>
            <p>
                info@kristinastroy.ru
            </p>
            ____________________________________________________________________________________________________________________________
            <p>
                Приемная директора:
            </p>
            <p>
                тел. 8 (863) 253-85-10
                kristina.firma@mail.ru
            </p>
            ____________________________________________________________________________________________________________________________
            <p>
                Юридический отдел

            </p>

            <p>
                тел. 8 (863) 251-83-55
            </p>


        </blockquote>
    </div>

    <footer>
        <div class="card mb-3">
            <img class="card-img-top" src="/img/footer.jpg" alt="Card image cap">
            <div class="card-body text-info">
                <h5 class="card-title">Связаться с нами</h5>
                <p class="card-body text-info">
                    Наши контакты:
                    Телефон +7 000 000 00 00    e-mail: samistroim@gmail.com
                </p>
            </div>
        </div>
    </footer>
</body>

WeBudget/Views/Home/Customers.cshtml
@{
    ViewBag.Title = "Клиентам";
}

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <title>О Компании</title>
    <link rel="stylesheet" href="~/Content/styles.css" type="text/css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300" type="text/css" />
    <title>Выравнивание фотографии по центру</title>
</head>

<div class="card mb-3">
    <img class="card-img-top" src="~/img/home.jpg" alt="Card image cap">
</div>

<style>
    .fig {
        text-align: center; /* Выравнивание по центру */
    }


    .center {
        width: 700px; /* Ширина элемента в пикселах */
        padding: 10px; /* Поля вокруг текста */
        margin: auto; /* Выравниваем по центру */
    }
</style>

<body>
    <div id="wrapper">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Меню</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link">
                        @Html.ActionLink("Главная", "Home", "Home")
                    </a>
                    <a class="nav-item nav-link">
                        @Html.ActionLink("О компании", "About", "Home")
                    </a>
                    <a class="nav-item nav-link">
                        @Html.ActionLink("Клиентам", "Customers", "Home")
                    </a>
                    <a class="nav-item nav-link">
                        @Html.ActionLink("Проекты", "ZdanieForPokupkas", "ZdanieForPokupka")
                    </a>
                    <a class="nav-item nav-link">
                        @Html.ActionLink("Контакты", "Contact", "Home")
                    </a>
                </div>
            </div>
        </nav>

        <div id="heading"></div>
        <section>
            <p>
                Сбербанк
            </p>
            <p>
                Сбербанк (является банком-партнером Строительной компании «Кристина») объявил о действующих ставках по Ипотеке.
            </p>
            <figure>
                <img src="/img/sber.png" width="320" height="175" alt="">
            </figure>

            <p>
                ___________________________________________________________________________________
            </p>
            <p>
                КБ "ЛОКО-Банк" (АО)
            </p>
            <p>
                Банк КБ "ЛОКО-Банк" (АО) предлагает ипотеку под 11.8% годовых
            </p>
            <figure>
                <img src="~/img/lockobank.png" width="320" height="175" alt="">
            </figure>

            <p>
                ___________________________________________________________________________________
            </p>

            <p>
                Газпромбанк
            </p>
            <p>
                Газпромбанк предлагает рефинансирование ипотечных кредитов под 9,5%!
            </p>
            <figure>
                <img src="~/img/gazprombank.png" width="320" height="175" alt="">
            </figure>
            <p>
                ___________________________________________________________________________________
            </p>


        </section>
    </div>

    <footer>
        <div class="card mb-3">
            <img class="card-img-top" src="/img/footer.jpg" alt="Card image cap">
            <div class="card-body text-info">
                <h5 class="card-title">Связаться с нами</h5>
                <p class="card-body text-info">
                    Наши контакты:
                    Телефон +7 000 000 00 00    e-mail: samistroim@gmail.com
                </p>
            </div>
        </div>
    </footer>

</body>

WeBudget/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Домашняя страница";
}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <title>Домашняя страница</title>
    <link rel="stylesheet" href="~/Content/styles.css" type="text/css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300" type="text/css" />
    <title>Выравнивание фотографии по центру</title>
</head>

<div class="card mb-3">
    <img class="card-img-top" src="~/img/home.jpg" alt="Card image cap">
</div>

<style>
    .fig {
        text-align: center; /* Выравнивание по центру */
    }


    .center {
        width: 700px; /* Ширина элемента в пикселах */
        padding: 10px; /* Поля вокруг текста */
        margin: auto; /* Выравниваем по центру */
    }
</style>

<body>
    <div id="wrapper">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Меню</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link">
                        @Html.ActionLink("Главная", "Home", "Home")
                    </a>
                    <a class="nav-item nav-link">
                        @Html.ActionLink("О компании", "About", "Home")
                    </a>
                    <a class="nav-item nav-link">
                        @Html.ActionLink("Клиентам", "Customers", "Home")
                    </a>
                    <a class="nav-item nav-link">
                        @Html.ActionLink("Проекты", "ZdanieForPokupkas", "ZdanieForPokupka")
                    </a>
                    <a class="nav-item nav-link">
                        @Html.ActionLink("Контакты", "Contact", "Home")
                    </a>
                </div>
            </div>
        </nav>





        <h1>
            Добро пожаловать на официальный сайт строительной компании «Сами построим»!
        </h1>
        <h1>
            <p>На нашем сайте вы можете ознакомиться со всеми проектами, строительство которых ведется на данный момент, посмотреть цены и планировки квартир в уже сданных объектах, записаться на просмотр или задать вопрос представителям компании или лично директору компани</p> Иванову Ивану Ивановичу.
        </h1>


    </div>

    <footer>
        <div class="card mb-3">
            <img class="card-img-top" src="~/img/footer.jpg" alt="Card image cap">
            <div class="card-body text-info">
                <h5 class="card-title">Связаться с нами</h5>
                <p class="card-body text-info">
                    Наши контакты:
                    Телефон +7 000 000 00 00    e-mail: samistroim@gmail.com
                </p>
            </div>
        </div>
    </footer>
</body> 