WeBudget/Models/Dohod.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WeBudget.Models
{
    public class Dohod
    {
        public int Id { get; set; }

        public int Day { get; set; }

        public int Month { get; set; }

        public double Sum { get; set; }

        public string Comment { get; set; }

        public virtual User User { get; set; }

    }
}

WeBudget/Controllers/DohodController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeBudget.Models;
using WeBudget.Service;

namespace WeBudget.Controllers
{
    public class DohodController : Controller
    {
        DohodService dohodservice = new DohodService();

        [HttpGet]
        public ActionResult EditDohod(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
           
            if (dohodservice.findDohodById(id) != null)
            {
                return View(dohodservice.findDohodById(id));
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult EditDohod(Dohod dohod)
        {
            dohodservice.Edit(dohod);
            return RedirectToAction("Dohods");
        }

        [HttpGet]
        public ActionResult CreateDohod()

        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateDohod(Dohod dohod)
        {
            dohodservice.Create(dohod);
            return RedirectToAction("Dohods");
        }

        public ActionResult DeleteDohod(int id)
        {
            dohodservice.Delete(id);
            return RedirectToAction("Dohods");
        }

        public ActionResult Dohods()

        {
            return View(dohodservice.getList());
        }
        protected override void Dispose(bool disposing)
        {
            dohodservice.Dispose();
            base.Dispose(disposing);
        }
    }
}

WeBudget/Views/Dohod/CreateDohod.cshtml
@{
    ViewBag.Title = "CreateDohod";
}


@model WeBudget.Models.Dohod

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавить доход</h2>

@using (Html.BeginForm())
{
    
    @Html.LabelFor(model => model.Day, "День")
    <br />
    @Html.EditorFor(model => model.Day)
    <br /><br />
    @Html.LabelFor(model => model.Month, "Месяц")
    <br />
    @Html.EditorFor(model => model.Month)
    <br /><br />
    @Html.LabelFor(model => model.Sum, "Сумма")
    <br />
    @Html.EditorFor(model => model.Sum)
    <br /><br />
    @Html.LabelFor(model => model.Comment, "Комментарий")
    <br />
    @Html.EditorFor(model => model.Comment)
    <br /><br />
    <input type="submit" value="Добавить" />
}

WeBudget/Views/Dohod/Dohods.cshtml
@{
    ViewBag.Title = "Dohods";
}



@model IEnumerable<WeBudget.Models.Dohod>
@{
    Layout = null;
}


<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <title>MуBudget</title>
    <link rel="stylesheet" href="~/Content/styles.css" type="text/css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300" type="text/css" />

    <title>Выравнивание фотографии по центру</title>
</head>




<style>
    .fig {
        text-align: center; /* Выравнивание по центру */
    }


    .center {
        width: 700px; /* Ширина элемента в пикселах */
        padding: 10px; /* Поля вокруг текста */
        margin: auto; /* Выравниваем по центру */
    }
</style>


<p class="fig">
    <img src="~/img/CY2NYGSvMto.jpg"
         width="1263" height="320" alt="Фотография">
</p>

<div class="center">
    <nav>
        <ul class="top-menu">
            <li><a href="index">ГЛАВНАЯ</a></li>
            <li class="About">О САЙТЕ</li>
            <li><a href="Contact">ОБРАТНАЯ СВЯЗЬ</a></li>
        </ul>
    </nav>
</div>
<aside>
    <nav>
        <ul class="aside-menu">
            <li><a href="Table">ТАБЛИЦА РАСХОДОВ</a></li>
            <li><a href="Dohodi">ДОХОДЫ И РАСХОДЫ</a></li>
            <li><a href="Kakebo">KAKEBO</a></li>

        </ul>
    </nav>
</aside>



<div class="center">
    <h2>Доходы</h2>


    @{ var grid = new WebGrid(Model); }
    <div>
        @grid.GetHtml(columns: grid.Columns(
                                                grid.Column("Id", "№"),
                                                grid.Column("Day", "День"),
                                                grid.Column("Month", "Месяц"),
                                                grid.Column("Sum", "Сумма"),
                                                grid.Column("Comment", "Комментарий"),
                                                grid.Column("Редактировать", format: @<a href="~/Dohod/EditDohod/@item.Id"> Редактировать</a>),
                                                    grid.Column("Удалить", format: @<a href="~/Dohod/DeleteDohod/@item.Id"> Удалить</a>)
                                                        ), tableStyle: "table-bordered")
    </div>
    <input type="button" value="Добавить" onClick='location.href="CreateDohod"'>

</div>

WeBudget/Views/Dohod/EditDohod.cshtml
@{
    ViewBag.Title = "EditDohod";
}

<h2>EditDohod</h2>

@{
    ViewBag.Title = "Редактировать доход";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model WeBudget.Models.Dohod
<h2>Доход № @Model.Id</h2>
@using (Html.BeginForm("EditDohod", "Dohod", FormMethod.Post))
{
<fieldset>
    @Html.HiddenFor(m => m.Id)
    <p>
        @Html.LabelFor(m => m.Day, "День")
        <br />
        @Html.EditorFor(m => m.Day)
    </p>
    <p>
        @Html.LabelFor(m => m.Month, "Месяц")
        <br />
        @Html.EditorFor(m => m.Month)

    </p>
    <p>
        @Html.LabelFor(m => m.Sum, "Сумма")
        <br />
        @Html.EditorFor(m => m.Sum)
    </p>

    <p>
        @Html.LabelFor(m => m.Comment, "Комментарий")
        <br />
        @Html.EditorFor(m => m.Comment)
    </p>
        @Html.HiddenFor(m => m.UserId)
    <p><input type="submit" value="Отправить" /></p>
</fieldset>
}